Repository kkinder/puepy, pull requests merged in 2024-08, with the labels that each got.

#35 Reduce the number of unnecessary underscores in ref generation.
  puepy/core.py
Labels: enhancement

#36 Add next_tick function for conveniently calling methods slightly later
  puepy/runtime.py
Labels: enhancement

#38 Upgrade to pyscript 2024.8.1
  examples/integrations/11_micropython_datetimes/index.html
  examples/integrations/12_ltk/index.html
  examples/integrations/13_jinja/index.html
  examples/tutorial/01_hello_world/index.html
  examples/tutorial/02_hello_name/index.html
  examples/tutorial/03_counter/index.html
  examples/tutorial/04_refs_problem/index.html
  examples/tutorial/04_refs_problem/solution.html
  examples/tutorial/05_watchers/index.html
  examples/tutorial/06_components/index.html
  examples/tutorial/07_routing/index.html
  examples/tutorial/08_libraries/index.html
  examples/tutorial/09_webcomponents/index.html
  examples/tutorial/10_full_app/index.html
Labels: dependencies

#39 Add experimental typeahead example
  examples/index.html
  examples/integrations/14_shoelace_autocomplete/index.html
  examples/integrations/14_shoelace_autocomplete/typeahead.py
Labels: documentation

#51 Update PyScript to version 2024.8.2 in examples
  examples/integrations/11_micropython_datetimes/index.html
  examples/integrations/12_ltk/index.html
  examples/integrations/13_jinja/index.html
  examples/integrations/14_shoelace_autocomplete/index.html
  examples/tutorial/01_hello_world/index.html
  examples/tutorial/02_hello_name/index.html
  examples/tutorial/03_counter/index.html
  examples/tutorial/04_refs_problem/index.html
  examples/tutorial/04_refs_problem/solution.html
  examples/tutorial/05_watchers/index.html
  examples/tutorial/06_components/index.html
  examples/tutorial/07_routing/index.html
  examples/tutorial/08_libraries/index.html
  examples/tutorial/09_webcomponents/index.html
  examples/tutorial/10_full_app/index.html
Labels: enhancement

#53 Update README.md
  README.md
Labels: documentation
